### ISSUE TITLE
403 error for some weapon images

### ISSUE THREAD

**Issue by todc** [LartTyler/MHWDB-API#82]
Hi,

First, thanks so much for building and hosting this API. It's fantastic!

I've noticed a bunch of weapon images which are returning 403 errors. Looks like they're being hosted by S3, so maybe they're configured to expire after X days, and that's causing it?

Here are the affected weapon IDs and URLs:

[11](https://assets.mhw-db.com/weapons/great-sword/ef4937214b610b35b945bc4906f96181c600d0b0.1b059957e9d5f1a76227303d5ce7e5ae.png)
[12](https://assets.mhw-db.com/weapons/great-sword/ef4937214b610b35b945bc4906f96181c600d0b0.1b059957e9d5f1a76227303d5ce7e5ae.png)
[31](https://assets.mhw-db.com/weapons/great-sword/fd8131c985b37b9b77aa7f506dbc9ed19a9b10b4.73cd3ea27498e0631c323c2e3d5a5d56.png)
[32](https://assets.mhw-db.com/weapons/great-sword/fd8131c985b37b9b77aa7f506dbc9ed19a9b10b4.73cd3ea27498e0631c323c2e3d5a5d56.png)
[39](https://assets.mhw-db.com/weapons/great-sword/9beaf7c3d0832f03fd15752d50f42a7cc6380da1.7d4b6aa96f8004aba7fa2da3dbbe2f0e.png)
[40](https://assets.mhw-db.com/weapons/great-sword/9beaf7c3d0832f03fd15752d50f42a7cc6380da1.7d4b6aa96f8004aba7fa2da3dbbe2f0e.png)
[134](https://assets.mhw-db.com/weapons/long-sword/b2d1b4005f679dbced3d7a70051eea640da1f389.aa554dd81559056101a7d833fb59cc49.png)
[135](https://assets.mhw-db.com/weapons/long-sword/b2d1b4005f679dbced3d7a70051eea640da1f389.aa554dd81559056101a7d833fb59cc49.png)
[136](https://assets.mhw-db.com/weapons/long-sword/b2d1b4005f679dbced3d7a70051eea640da1f389.aa554dd81559056101a7d833fb59cc49.png)
[173](https://assets.mhw-db.com/weapons/sword-and-shield/2066892866fdcb21ff07d37f9ebf7f3d022d38f2.55f961f6daea8a7cd8543180692c1aa8.png)
[174](https://assets.mhw-db.com/weapons/sword-and-shield/2066892866fdcb21ff07d37f9ebf7f3d022d38f2.55f961f6daea8a7cd8543180692c1aa8.png)
[175](https://assets.mhw-db.com/weapons/sword-and-shield/2066892866fdcb21ff07d37f9ebf7f3d022d38f2.55f961f6daea8a7cd8543180692c1aa8.png)
[176](https://assets.mhw-db.com/weapons/sword-and-shield/2066892866fdcb21ff07d37f9ebf7f3d022d38f2.55f961f6daea8a7cd8543180692c1aa8.png)
[177](https://assets.mhw-db.com/weapons/sword-and-shield/2066892866fdcb21ff07d37f9ebf7f3d022d38f2.55f961f6daea8a7cd8543180692c1aa8.png)
[180](https://assets.mhw-db.com/weapons/sword-and-shield/5364536e3e78ef8522589125d5af7f4b3780c0c7.a60928eba41aed7a4e5e69751128043b.png)
[181](https://assets.mhw-db.com/weapons/sword-and-shield/5364536e3e78ef8522589125d5af7f4b3780c0c7.a60928eba41aed7a4e5e69751128043b.png)
[184](https://assets.mhw-db.com/weapons/sword-and-shield/2c911cdac51c24240bd48931e0054fd04fa0ec97.510de2dfe0588ba9aeb76db84a321c2a.png)
[185](https://assets.mhw-db.com/weapons/sword-and-shield/2c911cdac51c24240bd48931e0054fd04fa0ec97.510de2dfe0588ba9aeb76db84a321c2a.png)
[186](https://assets.mhw-db.com/weapons/sword-and-shield/2c911cdac51c24240bd48931e0054fd04fa0ec97.510de2dfe0588ba9aeb76db84a321c2a.png)
[197](https://assets.mhw-db.com/weapons/sword-and-shield/793755f8d1a5998279f9eb607a319ff888d40076.85a9ebdb489ce633380ad97ac4a9a3d0.png)
[198](https://assets.mhw-db.com/weapons/sword-and-shield/793755f8d1a5998279f9eb607a319ff888d40076.85a9ebdb489ce633380ad97ac4a9a3d0.png)
[203](https://assets.mhw-db.com/weapons/sword-and-shield/057e0fce37413313afb22160bfdbdedd86392647.a2f06f5bc94cae4a7564a4db2767877f.png)
[204](https://assets.mhw-db.com/weapons/sword-and-shield/057e0fce37413313afb22160bfdbdedd86392647.a2f06f5bc94cae4a7564a4db2767877f.png)
[205](https://assets.mhw-db.com/weapons/sword-and-shield/057e0fce37413313afb22160bfdbdedd86392647.a2f06f5bc94cae4a7564a4db2767877f.png)
[222](https://assets.mhw-db.com/weapons/sword-and-shield/68dc5976f54452f462e1100dddfb95eac0e6ac68.d6d6ea5c25c8355fddd8f630b01b9957.png)
[223](https://assets.mhw-db.com/weapons/sword-and-shield/f271b9991d9c1cdfdb971ea40857bea3060cb642.af9c75ae45ad3a27b806dcea6fa7c688.png)
[224](https://assets.mhw-db.com/weapons/sword-and-shield/f271b9991d9c1cdfdb971ea40857bea3060cb642.af9c75ae45ad3a27b806dcea6fa7c688.png)
[230](https://assets.mhw-db.com/weapons/sword-and-shield/1dabee838a9e7a70d08b6acfc5cf69224acad5a6.203eceffceb6c35110e7414cf3453abd.png)
[231](https://assets.mhw-db.com/weapons/sword-and-shield/1dabee838a9e7a70d08b6acfc5cf69224acad5a6.203eceffceb6c35110e7414cf3453abd.png)
[232](https://assets.mhw-db.com/weapons/sword-and-shield/1dabee838a9e7a70d08b6acfc5cf69224acad5a6.203eceffceb6c35110e7414cf3453abd.png)
[385](https://assets.mhw-db.com/weapons/hammer/1e01e2b5390e8611d08d4dbb199285ab8fb98889.df682ed39a181ad21ffe72918ec63ba7.png)
[386](https://assets.mhw-db.com/weapons/hammer/1e01e2b5390e8611d08d4dbb199285ab8fb98889.df682ed39a181ad21ffe72918ec63ba7.png)
[441](https://assets.mhw-db.com/weapons/hunting-horn/423b8d55a6d8b7a05938cd160b95cd6b0daeb902.dcc0d400ecf9dabdd346158669978606.png)
[442](https://assets.mhw-db.com/weapons/hunting-horn/423b8d55a6d8b7a05938cd160b95cd6b0daeb902.dcc0d400ecf9dabdd346158669978606.png)
[443](https://assets.mhw-db.com/weapons/hunting-horn/423b8d55a6d8b7a05938cd160b95cd6b0daeb902.dcc0d400ecf9dabdd346158669978606.png)
[447](https://assets.mhw-db.com/weapons/hunting-horn/fa631fc67881c55f675e886a3f7985166cd2432e.632898ceb347634e9dafd43299491181.png)
[448](https://assets.mhw-db.com/weapons/hunting-horn/fa631fc67881c55f675e886a3f7985166cd2432e.632898ceb347634e9dafd43299491181.png)
[449](https://assets.mhw-db.com/weapons/hunting-horn/fa631fc67881c55f675e886a3f7985166cd2432e.632898ceb347634e9dafd43299491181.png)
[450](https://assets.mhw-db.com/weapons/hunting-horn/55a7d00958539fd650e270f9139a734a05b1a137.fdf5c370ef8d699d520f16c6f5dfa082.png)
[451](https://assets.mhw-db.com/weapons/hunting-horn/55a7d00958539fd650e270f9139a734a05b1a137.fdf5c370ef8d699d520f16c6f5dfa082.png)
[452](https://assets.mhw-db.com/weapons/hunting-horn/1e37b9d7ede00d0cf7d2cd10333e0fe4af96dbe1.5cf9802f4b5d81fc4b6f2516139d68c5.png)
[453](https://assets.mhw-db.com/weapons/hunting-horn/1e37b9d7ede00d0cf7d2cd10333e0fe4af96dbe1.5cf9802f4b5d81fc4b6f2516139d68c5.png)
[464](https://assets.mhw-db.com/weapons/hunting-horn/55373ddb9a687223e590792cec79a61fb764cced.4e5e5eabbd2dd9d948cff21907e223f5.png)
[465](https://assets.mhw-db.com/weapons/hunting-horn/55373ddb9a687223e590792cec79a61fb764cced.4e5e5eabbd2dd9d948cff21907e223f5.png)
[466](https://assets.mhw-db.com/weapons/hunting-horn/55373ddb9a687223e590792cec79a61fb764cced.4e5e5eabbd2dd9d948cff21907e223f5.png)
[467](https://assets.mhw-db.com/weapons/hunting-horn/f049cf20961d468f43cfb30281eb5c11b7103057.6c2f264d3ffe8ec36fd900e0b682c4ef.png)
[468](https://assets.mhw-db.com/weapons/hunting-horn/f049cf20961d468f43cfb30281eb5c11b7103057.6c2f264d3ffe8ec36fd900e0b682c4ef.png)
[469](https://assets.mhw-db.com/weapons/hunting-horn/f049cf20961d468f43cfb30281eb5c11b7103057.6c2f264d3ffe8ec36fd900e0b682c4ef.png)
[470](https://assets.mhw-db.com/weapons/hunting-horn/f049cf20961d468f43cfb30281eb5c11b7103057.6c2f264d3ffe8ec36fd900e0b682c4ef.png)
[471](https://assets.mhw-db.com/weapons/hunting-horn/f049cf20961d468f43cfb30281eb5c11b7103057.6c2f264d3ffe8ec36fd900e0b682c4ef.png)
[474](https://assets.mhw-db.com/weapons/hunting-horn/9f7a0fcbefa30d50eace1a16272cf1101b44ec59.25651eb5c97f17dea662b26305901a95.png)
[475](https://assets.mhw-db.com/weapons/hunting-horn/9f7a0fcbefa30d50eace1a16272cf1101b44ec59.25651eb5c97f17dea662b26305901a95.png)
[476](https://assets.mhw-db.com/weapons/hunting-horn/b89640ac954b24ff4f98577478bc82664b945abf.9a0f72ba9f994888b9a3a01bf63f742e.png)
[477](https://assets.mhw-db.com/weapons/hunting-horn/b89640ac954b24ff4f98577478bc82664b945abf.9a0f72ba9f994888b9a3a01bf63f742e.png)
[478](https://assets.mhw-db.com/weapons/hunting-horn/b89640ac954b24ff4f98577478bc82664b945abf.9a0f72ba9f994888b9a3a01bf63f742e.png)
[492](https://assets.mhw-db.com/weapons/hunting-horn/7ddf5d781051c18c6b8e7986183db3e99d6d3cd2.33be4167e4778fd07eca0c2692340ee7.png)
[493](https://assets.mhw-db.com/weapons/hunting-horn/7ddf5d781051c18c6b8e7986183db3e99d6d3cd2.33be4167e4778fd07eca0c2692340ee7.png)
[494](https://assets.mhw-db.com/weapons/hunting-horn/7ddf5d781051c18c6b8e7986183db3e99d6d3cd2.33be4167e4778fd07eca0c2692340ee7.png)
[495](https://assets.mhw-db.com/weapons/hunting-horn/a426b8b4121bba20ad8d926ac9f6bd6778d8bae2.465f0af9d007521ba878a3f2aac6744d.png)
[496](https://assets.mhw-db.com/weapons/hunting-horn/a426b8b4121bba20ad8d926ac9f6bd6778d8bae2.465f0af9d007521ba878a3f2aac6744d.png)
[497](https://assets.mhw-db.com/weapons/hunting-horn/a426b8b4121bba20ad8d926ac9f6bd6778d8bae2.465f0af9d007521ba878a3f2aac6744d.png)
[498](https://assets.mhw-db.com/weapons/hunting-horn/1679cd2d3323d251615e05a2a0c5e8d4be52ef6e.f1a903677d609cacea0f49ab69511de4.png)
[499](https://assets.mhw-db.com/weapons/hunting-horn/1679cd2d3323d251615e05a2a0c5e8d4be52ef6e.f1a903677d609cacea0f49ab69511de4.png)
[506](https://assets.mhw-db.com/weapons/hunting-horn/be53ed642277c7718f8503320d88969fe6d93bf1.d51128adc009b80808c2119ec98f7ea6.png)
[511](https://assets.mhw-db.com/weapons/hunting-horn/bbb30423c866b343bc19c0791cd2ad9ecfa1d9a9.621ad70aa35bc48a061958166a48a41f.png)
[523](https://assets.mhw-db.com/weapons/lance/e82c2ae8d6b84463c4ab893948e2786a131cfc97.2ae92679f059a9082bdd4ccb62a47453.png)
[531](https://assets.mhw-db.com/weapons/lance/26bac9db0b5f56e72eb4928e17d26a5c7f31008b.dda7e9421b9b49adca8e84e5666333fa.png)
[532](https://assets.mhw-db.com/weapons/lance/26bac9db0b5f56e72eb4928e17d26a5c7f31008b.dda7e9421b9b49adca8e84e5666333fa.png)
[533](https://assets.mhw-db.com/weapons/lance/26bac9db0b5f56e72eb4928e17d26a5c7f31008b.dda7e9421b9b49adca8e84e5666333fa.png)
[544](https://assets.mhw-db.com/weapons/lance/e2d08af0dbdbda5ff234973eea68890abcb24f3c.b4edc58753df6facf3913ab4776a76f5.png)
[545](https://assets.mhw-db.com/weapons/lance/e2d08af0dbdbda5ff234973eea68890abcb24f3c.b4edc58753df6facf3913ab4776a76f5.png)
[546](https://assets.mhw-db.com/weapons/lance/e2d08af0dbdbda5ff234973eea68890abcb24f3c.b4edc58753df6facf3913ab4776a76f5.png)
[549](https://assets.mhw-db.com/weapons/lance/f56a2824c9346113336aea120367c0d309499a39.c37e249d0f16d72b406cff93f5b3bf08.png)
[550](https://assets.mhw-db.com/weapons/lance/e8594e4fbbd486b12023d433aa87622bd516cb5c.44a932c0c4732fbeca1aca492474aac6.png)
[551](https://assets.mhw-db.com/weapons/lance/e8594e4fbbd486b12023d433aa87622bd516cb5c.44a932c0c4732fbeca1aca492474aac6.png)
[552](https://assets.mhw-db.com/weapons/lance/9136e23f21fe79b71cb295b15fada16fb8456753.dcc96acef5976905b0335aa47648a435.png)
[553](https://assets.mhw-db.com/weapons/lance/9136e23f21fe79b71cb295b15fada16fb8456753.dcc96acef5976905b0335aa47648a435.png)
[554](https://assets.mhw-db.com/weapons/lance/9136e23f21fe79b71cb295b15fada16fb8456753.dcc96acef5976905b0335aa47648a435.png)
[608](https://assets.mhw-db.com/weapons/gunlance/ff29c8508f25e0868bc30def18f04eef6770b1c0.bd514b4d02186b4d4d8544268b441586.png)
[609](https://assets.mhw-db.com/weapons/gunlance/ff29c8508f25e0868bc30def18f04eef6770b1c0.bd514b4d02186b4d4d8544268b441586.png)
[610](https://assets.mhw-db.com/weapons/gunlance/ff29c8508f25e0868bc30def18f04eef6770b1c0.bd514b4d02186b4d4d8544268b441586.png)
[619](https://assets.mhw-db.com/weapons/gunlance/13085b0831787712ce72c3a66a6f90af76bd6eae.d68b940476f86ba7d138846ff4ed0681.png)
[620](https://assets.mhw-db.com/weapons/gunlance/13085b0831787712ce72c3a66a6f90af76bd6eae.d68b940476f86ba7d138846ff4ed0681.png)
[633](https://assets.mhw-db.com/weapons/gunlance/ae7e3215e44474d8883e8eb26209a0d9895fad5d.c70de25ce2008e4141ee545e09f41564.png)
[634](https://assets.mhw-db.com/weapons/gunlance/ae7e3215e44474d8883e8eb26209a0d9895fad5d.c70de25ce2008e4141ee545e09f41564.png)
[635](https://assets.mhw-db.com/weapons/gunlance/ae7e3215e44474d8883e8eb26209a0d9895fad5d.c70de25ce2008e4141ee545e09f41564.png)
[636](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[637](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[638](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[639](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[640](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[656](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[657](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[658](https://assets.mhw-db.com/weapons/gunlance/95caf4d318354fdd948d9fbc0d895ee7bded536c.4a7eff144b8b2878d1a3c0c740767a53.png)
[731](https://assets.mhw-db.com/weapons/switch-axe/1631655108d6e5b1adc7a78c80077a0ed38eba9e.6d63a877fd8835f833d4dfc3fc504e97.png)
[732](https://assets.mhw-db.com/weapons/switch-axe/1631655108d6e5b1adc7a78c80077a0ed38eba9e.6d63a877fd8835f833d4dfc3fc504e97.png)
[733](https://assets.mhw-db.com/weapons/switch-axe/1631655108d6e5b1adc7a78c80077a0ed38eba9e.6d63a877fd8835f833d4dfc3fc504e97.png)
[751](https://assets.mhw-db.com/weapons/switch-axe/01cd2d2fea738c73b40be6970800176ce8d5175e.865fc30321d4db69632eb409f652e739.png)
[752](https://assets.mhw-db.com/weapons/switch-axe/01cd2d2fea738c73b40be6970800176ce8d5175e.865fc30321d4db69632eb409f652e739.png)
[831](https://assets.mhw-db.com/weapons/insect-glaive/491dfe632699628f1f242e5b1cbe32bd0a385a7d.0252c014013199a80e92b065dfee5916.png)
[832](https://assets.mhw-db.com/weapons/insect-glaive/491dfe632699628f1f242e5b1cbe32bd0a385a7d.0252c014013199a80e92b065dfee5916.png)
[833](https://assets.mhw-db.com/weapons/insect-glaive/491dfe632699628f1f242e5b1cbe32bd0a385a7d.0252c014013199a80e92b065dfee5916.png)
[868](https://assets.mhw-db.com/weapons/insect-glaive/7e304dd87a71e13b16ffc149311b333f38f654c9.81eaa72cac03fa54360a0b5b68172777.png)
[869](https://assets.mhw-db.com/weapons/insect-glaive/7e304dd87a71e13b16ffc149311b333f38f654c9.81eaa72cac03fa54360a0b5b68172777.png)
[870](https://assets.mhw-db.com/weapons/insect-glaive/7e304dd87a71e13b16ffc149311b333f38f654c9.81eaa72cac03fa54360a0b5b68172777.png)
[899](https://assets.mhw-db.com/weapons/insect-glaive/f880652ecf25b4209e0607891409c57aaf815aef.285b70312e410bf86fad64be64a77d67.png)
[900](https://assets.mhw-db.com/weapons/insect-glaive/f880652ecf25b4209e0607891409c57aaf815aef.285b70312e410bf86fad64be64a77d67.png)
[909](https://assets.mhw-db.com/weapons/insect-glaive/20672a6ca6f45d041c3a8baf302f7478a731ecb0.b7e1edf42f827635c528723243caf443.png)
[922](https://assets.mhw-db.com/weapons/light-bowgun/7c019e32dbab17b5fe1d2da45bbe97d3937f7f92.bbb0e716d4a1b83d5a488851e47c4587.png)
[923](https://assets.mhw-db.com/weapons/light-bowgun/7c019e32dbab17b5fe1d2da45bbe97d3937f7f92.bbb0e716d4a1b83d5a488851e47c4587.png)
[924](https://assets.mhw-db.com/weapons/light-bowgun/3b3b200a901e429bec629f95e02e47c7de632abb.1502f5e075a27501e6bf67105bf584c4.png)
[925](https://assets.mhw-db.com/weapons/light-bowgun/3b3b200a901e429bec629f95e02e47c7de632abb.1502f5e075a27501e6bf67105bf584c4.png)
[926](https://assets.mhw-db.com/weapons/light-bowgun/3b3b200a901e429bec629f95e02e47c7de632abb.1502f5e075a27501e6bf67105bf584c4.png)
[937](https://assets.mhw-db.com/weapons/light-bowgun/ea80b094c6d64eb56151a0b6835688b990711da3.be13c07ec82a4288ada817608084e5cf.png)
[938](https://assets.mhw-db.com/weapons/light-bowgun/ea80b094c6d64eb56151a0b6835688b990711da3.be13c07ec82a4288ada817608084e5cf.png)
[963](https://assets.mhw-db.com/weapons/light-bowgun/b6293dffd2073c43ab3ab5735f4514c5f9f7f407.ff206cd1167a246a5eb16a04f57aa09a.png)
[964](https://assets.mhw-db.com/weapons/light-bowgun/b6293dffd2073c43ab3ab5735f4514c5f9f7f407.ff206cd1167a246a5eb16a04f57aa09a.png)
[965](https://assets.mhw-db.com/weapons/light-bowgun/b6293dffd2073c43ab3ab5735f4514c5f9f7f407.ff206cd1167a246a5eb16a04f57aa09a.png)
[979](https://assets.mhw-db.com/weapons/light-bowgun/05225577c733b154d76264f372cd546b2c82737c.d1591901b279a41a54b6ee35e174037e.png)
[980](https://assets.mhw-db.com/weapons/light-bowgun/05225577c733b154d76264f372cd546b2c82737c.d1591901b279a41a54b6ee35e174037e.png)
[999](https://assets.mhw-db.com/weapons/heavy-bowgun/75380e79e73e1c789a530e1de68f8a8e5d7a8d02.25ee66d59337cee62ed50a6959058052.png)
[1000](https://assets.mhw-db.com/weapons/heavy-bowgun/75380e79e73e1c789a530e1de68f8a8e5d7a8d02.25ee66d59337cee62ed50a6959058052.png)
[1001](https://assets.mhw-db.com/weapons/heavy-bowgun/75380e79e73e1c789a530e1de68f8a8e5d7a8d02.25ee66d59337cee62ed50a6959058052.png)
[1012](https://assets.mhw-db.com/weapons/heavy-bowgun/991157f69f8052962938c23113b74eabd46e5cb7.ff8f9a5297c6fa56911cd7da1c710741.png)
[1013](https://assets.mhw-db.com/weapons/heavy-bowgun/991157f69f8052962938c23113b74eabd46e5cb7.ff8f9a5297c6fa56911cd7da1c710741.png)
[1023](https://assets.mhw-db.com/weapons/heavy-bowgun/d40c404331d831296f0b7a0e9fca9294c3a09b6f.9cc67e09e4335bcf160894ac9d5ad050.png)
[1024](https://assets.mhw-db.com/weapons/heavy-bowgun/d40c404331d831296f0b7a0e9fca9294c3a09b6f.9cc67e09e4335bcf160894ac9d5ad050.png)
[1040](https://assets.mhw-db.com/weapons/heavy-bowgun/25c71756849e31242056f5300b8659642932a2c5.75785ceaeda30acfcddb64c38a67d241.png)
[1054](https://assets.mhw-db.com/weapons/heavy-bowgun/3a0bc4226231f153e24fd8536ef33d27b43af0b6.001c57552ebdb283cb3eca8ab6ffbe85.png)
[1055](https://assets.mhw-db.com/weapons/heavy-bowgun/3a0bc4226231f153e24fd8536ef33d27b43af0b6.001c57552ebdb283cb3eca8ab6ffbe85.png)
[1056](https://assets.mhw-db.com/weapons/heavy-bowgun/2d275fd9e2c0e52c6c9435505667a9b601047bc5.dceccde6ab0b7a39f432b4a7582c9c0c.png)
[1057](https://assets.mhw-db.com/weapons/heavy-bowgun/2d275fd9e2c0e52c6c9435505667a9b601047bc5.dceccde6ab0b7a39f432b4a7582c9c0c.png)
[1058](https://assets.mhw-db.com/weapons/heavy-bowgun/2d275fd9e2c0e52c6c9435505667a9b601047bc5.dceccde6ab0b7a39f432b4a7582c9c0c.png)

**Comment by LartTyler** [comment]
Thanks for letting me know. S3 isn't configured to expire anything, but I think they may have failed to re-upload correctly during the last update. I'm going to push the images up to S3 again to see if it fixes it.

**Comment by LartTyler** [comment]
@todc Should be resolved now.

**Comment by todc** [comment]
Thanks @LartTyler!

I'm still seeing the same URLs at the /weapons endpoint, resulting in the same 403 errors. Maybe I'm getting a cached response though, so I'll take another look tomorrow.

**Comment by LartTyler** [comment]
Damn. I just realized I forgot to clear Cloudflare's cache when I pushed that update out, that's probably why you were still seeing the same URLs. I just cleared it, to be on the safe side. Let me know if you're still having issues.

**Comment by todc** [comment]
Yep, confirmed working now. Thanks much!
